site_name: Robot operációs rendszerek és fejlesztői ökoszisztémák

nav:
  - Robot operációs rendszerek és fejlesztői ökoszisztémák: index.md

theme:
  name: material
  language: hu
  favicon: img/favicon.ico

copyright: Copyright &copy; KUKA Hungária Kft.
