FROM ros:humble-ros-base
# You might need docker.io/ at the start

ARG USERNAME=rosdev
ARG UID=1000
ARG GID=$UID

# Set needed envs
ENV ROS_DOMAIN_ID=your_domain_id
# Required if communication with remote endpoint needed, too
# ENV FASTRTPS_DEFAULT_PROFILES_FILE=/home/rosdev/ros2_ws/fastdds_config.xml

# Install some additional packages
RUN apt-get update -q \
    && apt-get upgrade -q -y \
    && apt-get install -y --no-install-recommends \
    software-properties-common \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create and switch to user
RUN groupadd -g $GID $USERNAME \
    && useradd -lm -u $UID -g $USERNAME -s /bin/bash $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER $USERNAME

# Create workspace so that user own this directory
RUN mkdir -p /home/$USERNAME/ros2_ws/src
WORKDIR /home/$USERNAME/ros2_ws

# Copy configuration files
RUN echo 'source /opt/ros/'$ROS_DISTRO'/setup.bash' >> /home/$USERNAME/.bashrc \
    && echo 'source /home/'$USERNAME'/ros2_ws/install/setup.bash' >> /home/$USERNAME/.bashrc